### ISSUE TITLE
提示与  异星工厂模组汉化文本库重置版mod不兼容

### ISSUE THREAD

**Issue by Chow-Ray** [PlexPt/factorio-chinese#2]
提示与  异星工厂模组汉化文本库重置版mod不兼容，
看说明是基于重置版汉化制作，是否意味着可以删除重置版汉化mod？不需要在使用？
https://mods.factorio.com/mod/zhcnremake
![QQ截图20220125190241](https://user-images.githubusercontent.com/29678677/150965884-a06be2f3-4069-4504-92e3-4a5c39bba12f.png)

**Comment by PlexPt** [comment]
是
