### ISSUE TITLE
Space Exploration 翻译文本错误覆盖原版文本

### ISSUE THREAD

**Issue by yako0755** [PlexPt/factorio-chinese#23]
未曾启用 Space Exploration

<img width="534" alt="image" src="https://user-images.githubusercontent.com/36659715/187311080-51def795-7485-415e-bdba-f1ee3816f343.png">

禁用本翻译 Mod 后恢复正常，推测本翻译 Mod 中原版插件分享塔的描述文本被 Space Exploration 所属的翻译描述文本错误覆盖

<img width="421" alt="image" src="https://user-images.githubusercontent.com/36659715/187311132-75badd72-9ca6-4476-aa43-6569394de9d7.png">

<img width="549" alt="image" src="https://user-images.githubusercontent.com/36659715/187311316-95cdf57c-e4d2-4d58-8f92-c36d961597e5.png">

**Comment by PlexPt** [comment]
是这样的

**Comment by PlexPt** [comment]
已修复
