### ISSUE TITLE
将未安装的mod的中文翻译添加到游戏中并覆盖了原版翻译

### ISSUE THREAD

**Issue by MuuuShin** [PlexPt/factorio-chinese#9]
未使用Schall Uranium Processing mod，在近一次翻译mod更新后，翻译mod却将铀235与238翻译成了超浓缩铀与贫铀。将翻译mod禁用后恢复铀235与238翻译。
下图为未使用Schall Uranium Processing的证明（事实上要不是出现翻译覆盖，我也不会知道这个mod
![image](https://user-images.githubusercontent.com/97760035/162601364-fe072e19-c0ce-490b-96c9-7de5c54ad3a0.png)
下图为证明应是Schall Uranium Processing的翻译覆盖了游戏原版
![image](https://user-images.githubusercontent.com/97760035/162601422-73799b2d-5b1a-4240-ae3b-7d9f15f82086.png)

**Comment by PlexPt** [comment]
👌🏻

**Comment by PlexPt** [comment]
fixed
